# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1b959a53e79da33a17c8799ae1f11ae09a39d26ed3c45265e28ccc5cb35ee1e254ab22ee4ed4fb90d92f6b7bedc9c743a275ed4ce35421e4d862c60d78d1fa5

test:
  secret_key_base: 05ff21ae899906b59d85df26f8581178630c89d61b71ec3851c7391efc128cd52a7323f4f23f218be5614f4de7ced90b6354db2299b754746fadf81878542e34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
