Chord.create!([
  {root: "C", quality: "Major", audio_file: nil, name: "C Maj"},
  {root: "C", quality: "Minor", audio_file: nil, name: "c min"},
  {root: "C", quality: "Diminished", audio_file: nil, name: "c dim"},
  {root: "C#", quality: "Major", audio_file: nil, name: "C# Maj"},
  {root: "C#", quality: "Minor", audio_file: nil, name: "c# min"},
  {root: "C#", quality: "Diminished", audio_file: nil, name: "c# dim"},
  {root: "Db", quality: "Major", audio_file: nil, name: "Db Maj"},
  {root: "Db", quality: "Minor", audio_file: nil, name: "db min"},
  {root: "Db", quality: "Diminished", audio_file: nil, name: "db dim"},
  {root: "D", quality: "Major", audio_file: nil, name: "D Maj"},
  {root: "D", quality: "Minor", audio_file: nil, name: "d min"},
  {root: "D", quality: "Diminished", audio_file: nil, name: "d dim"},
  {root: "D#", quality: "Major", audio_file: nil, name: "D# Maj"},
  {root: "D#", quality: "Minor", audio_file: nil, name: "d# min"},
  {root: "D#", quality: "Diminished", audio_file: nil, name: "d# dim"},
  {root: "Eb", quality: "Major", audio_file: nil, name: "Eb Maj"},
  {root: "Eb", quality: "Minor", audio_file: nil, name: "eb min"},
  {root: "Eb", quality: "Diminished", audio_file: nil, name: "eb dim"},
  {root: "E", quality: "Major", audio_file: nil, name: "E Maj"},
  {root: "E", quality: "Minor", audio_file: nil, name: "e min"},
  {root: "E", quality: "Diminished", audio_file: nil, name: "e dim"},
  {root: "F", quality: "Major", audio_file: nil, name: "F Maj"},
  {root: "F", quality: "Minor", audio_file: nil, name: "f min"},
  {root: "F", quality: "Diminished", audio_file: nil, name: "f dim"},
  {root: "F#", quality: "Major", audio_file: nil, name: "F# Maj"},
  {root: "F#", quality: "Minor", audio_file: nil, name: "f# min"},
  {root: "F#", quality: "Diminished", audio_file: nil, name: "f# dim"},
  {root: "Gb", quality: "Major", audio_file: nil, name: "Gb Maj"},
  {root: "Gb", quality: "Minor", audio_file: nil, name: "gb min"},
  {root: "Gb", quality: "Diminished", audio_file: nil, name: "gb dim"},
  {root: "G", quality: "Major", audio_file: nil, name: "G Maj"},
  {root: "G", quality: "Minor", audio_file: nil, name: "g min"},
  {root: "G", quality: "Diminished", audio_file: nil, name: "g dim"},
  {root: "G#", quality: "Major", audio_file: nil, name: "G# Maj"},
  {root: "G#", quality: "Minor", audio_file: nil, name: "g# min"},
  {root: "G#", quality: "Diminished", audio_file: nil, name: "g# dim"},
  {root: "Ab", quality: "Major", audio_file: nil, name: "Ab Maj"},
  {root: "Ab", quality: "Minor", audio_file: nil, name: "ab min"},
  {root: "Ab", quality: "Diminished", audio_file: nil, name: "ab dim"},
  {root: "A", quality: "Major", audio_file: nil, name: "A Maj"},
  {root: "A", quality: "Minor", audio_file: nil, name: "a min"},
  {root: "A", quality: "Diminished", audio_file: nil, name: "a dim"},
  {root: "A#", quality: "Major", audio_file: nil, name: "A# Maj"},
  {root: "A#", quality: "Minor", audio_file: nil, name: "a# min"},
  {root: "A#", quality: "Diminished", audio_file: nil, name: "a# dim"},
  {root: "Bb", quality: "Major", audio_file: nil, name: "Bb Maj"},
  {root: "Bb", quality: "Minor", audio_file: nil, name: "bb min"},
  {root: "Bb", quality: "Diminished", audio_file: nil, name: "bb dim"},
  {root: "B", quality: "Major", audio_file: nil, name: "B Maj"},
  {root: "B", quality: "Minor", audio_file: nil, name: "b min"},
  {root: "B", quality: "Diminished", audio_file: nil, name: "b dim"},
  {root: "Cb", quality: "Major", audio_file: nil, name: "Cb Maj"},
  {root: "Cb", quality: "Minor", audio_file: nil, name: "cb min"},
  {root: "Cb", quality: "Diminished", audio_file: nil, name: "cb dim"},
  {root: "E#", quality: "Major", audio_file: nil, name: "E# Maj"},
  {root: "E#", quality: "Minor", audio_file: nil, name: "e# min"},
  {root: "E#", quality: "Diminished", audio_file: nil, name: "e# dim"},
  {root: "B#", quality: "Major", audio_file: nil, name: "B# Maj"},
  {root: "B#", quality: "Minor", audio_file: nil, name: "b# min"},
  {root: "B#", quality: "Diminished", audio_file: nil, name: "b# dim"},
  {root: "Fb", quality: "Major", audio_file: nil, name: "Fb Maj"},
  {root: "Fb", quality: "Minor", audio_file: nil, name: "fb min"},
  {root: "Fb", quality: "Diminished", audio_file: nil, name: "fb dim"}
])
ChordByKey.create!([
  {key_id: 1, chord_id: 4},
  {key_id: 1, chord_id: 14},
  {key_id: 1, chord_id: 62},
  {key_id: 1, chord_id: 25},
  {key_id: 1, chord_id: 34},
  {key_id: 1, chord_id: 44},
  {key_id: 1, chord_id: 67},
  {key_id: 2, chord_id: 25},
  {key_id: 2, chord_id: 35},
  {key_id: 2, chord_id: 44},
  {key_id: 2, chord_id: 49},
  {key_id: 2, chord_id: 4},
  {key_id: 2, chord_id: 14},
  {key_id: 2, chord_id: 63},
  {key_id: 3, chord_id: 49},
  {key_id: 3, chord_id: 5},
  {key_id: 3, chord_id: 14},
  {key_id: 3, chord_id: 19},
  {key_id: 3, chord_id: 25},
  {key_id: 3, chord_id: 35},
  {key_id: 3, chord_id: 45},
  {key_id: 4, chord_id: 19},
  {key_id: 4, chord_id: 26},
  {key_id: 4, chord_id: 35},
  {key_id: 4, chord_id: 40},
  {key_id: 4, chord_id: 49},
  {key_id: 4, chord_id: 5},
  {key_id: 4, chord_id: 15},
  {key_id: 5, chord_id: 40},
  {key_id: 5, chord_id: 50},
  {key_id: 5, chord_id: 5},
  {key_id: 5, chord_id: 10},
  {key_id: 5, chord_id: 19},
  {key_id: 5, chord_id: 26},
  {key_id: 5, chord_id: 36},
  {key_id: 6, chord_id: 10},
  {key_id: 6, chord_id: 20},
  {key_id: 6, chord_id: 26},
  {key_id: 6, chord_id: 31},
  {key_id: 6, chord_id: 40},
  {key_id: 6, chord_id: 50},
  {key_id: 6, chord_id: 6},
  {key_id: 7, chord_id: 31},
  {key_id: 7, chord_id: 41},
  {key_id: 7, chord_id: 50},
  {key_id: 7, chord_id: 1},
  {key_id: 7, chord_id: 10},
  {key_id: 7, chord_id: 20},
  {key_id: 7, chord_id: 27},
  {key_id: 8, chord_id: 1},
  {key_id: 8, chord_id: 11},
  {key_id: 8, chord_id: 20},
  {key_id: 8, chord_id: 22},
  {key_id: 8, chord_id: 31},
  {key_id: 8, chord_id: 41},
  {key_id: 8, chord_id: 51},
  {key_id: 9, chord_id: 22},
  {key_id: 9, chord_id: 32},
  {key_id: 9, chord_id: 41},
  {key_id: 9, chord_id: 46},
  {key_id: 9, chord_id: 1},
  {key_id: 9, chord_id: 11},
  {key_id: 9, chord_id: 21},
  {key_id: 10, chord_id: 46},
  {key_id: 10, chord_id: 2},
  {key_id: 10, chord_id: 11},
  {key_id: 10, chord_id: 16},
  {key_id: 10, chord_id: 22},
  {key_id: 10, chord_id: 32},
  {key_id: 10, chord_id: 42},
  {key_id: 11, chord_id: 16},
  {key_id: 11, chord_id: 23},
  {key_id: 11, chord_id: 32},
  {key_id: 11, chord_id: 37},
  {key_id: 11, chord_id: 46},
  {key_id: 11, chord_id: 2},
  {key_id: 11, chord_id: 12},
  {key_id: 12, chord_id: 37},
  {key_id: 12, chord_id: 47},
  {key_id: 12, chord_id: 2},
  {key_id: 12, chord_id: 7},
  {key_id: 12, chord_id: 16},
  {key_id: 12, chord_id: 23},
  {key_id: 12, chord_id: 33},
  {key_id: 13, chord_id: 7},
  {key_id: 13, chord_id: 17},
  {key_id: 13, chord_id: 23},
  {key_id: 13, chord_id: 28},
  {key_id: 13, chord_id: 37},
  {key_id: 13, chord_id: 47},
  {key_id: 13, chord_id: 3},
  {key_id: 14, chord_id: 28},
  {key_id: 14, chord_id: 38},
  {key_id: 14, chord_id: 47},
  {key_id: 14, chord_id: 52},
  {key_id: 14, chord_id: 7},
  {key_id: 14, chord_id: 17},
  {key_id: 14, chord_id: 24},
  {key_id: 15, chord_id: 52},
  {key_id: 15, chord_id: 8},
  {key_id: 15, chord_id: 17},
  {key_id: 15, chord_id: 68},
  {key_id: 15, chord_id: 28},
  {key_id: 15, chord_id: 38},
  {key_id: 15, chord_id: 48},
  {key_id: 16, chord_id: 44},
  {key_id: 16, chord_id: 67},
  {key_id: 16, chord_id: 4},
  {key_id: 16, chord_id: 14},
  {key_id: 16, chord_id: 62},
  {key_id: 16, chord_id: 25},
  {key_id: 16, chord_id: 34},
  {key_id: 17, chord_id: 14},
  {key_id: 17, chord_id: 63},
  {key_id: 17, chord_id: 25},
  {key_id: 17, chord_id: 35},
  {key_id: 17, chord_id: 44},
  {key_id: 17, chord_id: 49},
  {key_id: 17, chord_id: 4},
  {key_id: 18, chord_id: 35},
  {key_id: 18, chord_id: 45},
  {key_id: 18, chord_id: 49},
  {key_id: 18, chord_id: 5},
  {key_id: 18, chord_id: 14},
  {key_id: 18, chord_id: 19},
  {key_id: 18, chord_id: 25},
  {key_id: 19, chord_id: 5},
  {key_id: 19, chord_id: 15},
  {key_id: 19, chord_id: 19},
  {key_id: 19, chord_id: 26},
  {key_id: 19, chord_id: 35},
  {key_id: 19, chord_id: 40},
  {key_id: 19, chord_id: 49},
  {key_id: 20, chord_id: 26},
  {key_id: 20, chord_id: 36},
  {key_id: 20, chord_id: 40},
  {key_id: 20, chord_id: 50},
  {key_id: 20, chord_id: 5},
  {key_id: 20, chord_id: 10},
  {key_id: 20, chord_id: 19},
  {key_id: 21, chord_id: 50},
  {key_id: 21, chord_id: 6},
  {key_id: 21, chord_id: 10},
  {key_id: 21, chord_id: 20},
  {key_id: 21, chord_id: 26},
  {key_id: 21, chord_id: 31},
  {key_id: 21, chord_id: 40},
  {key_id: 22, chord_id: 20},
  {key_id: 22, chord_id: 27},
  {key_id: 22, chord_id: 31},
  {key_id: 22, chord_id: 41},
  {key_id: 22, chord_id: 50},
  {key_id: 22, chord_id: 1},
  {key_id: 22, chord_id: 10},
  {key_id: 23, chord_id: 41},
  {key_id: 23, chord_id: 51},
  {key_id: 23, chord_id: 1},
  {key_id: 23, chord_id: 11},
  {key_id: 23, chord_id: 20},
  {key_id: 23, chord_id: 22},
  {key_id: 23, chord_id: 31},
  {key_id: 24, chord_id: 11},
  {key_id: 24, chord_id: 21},
  {key_id: 24, chord_id: 22},
  {key_id: 24, chord_id: 32},
  {key_id: 24, chord_id: 41},
  {key_id: 24, chord_id: 46},
  {key_id: 24, chord_id: 1},
  {key_id: 25, chord_id: 32},
  {key_id: 25, chord_id: 42},
  {key_id: 25, chord_id: 46},
  {key_id: 25, chord_id: 2},
  {key_id: 25, chord_id: 11},
  {key_id: 25, chord_id: 16},
  {key_id: 25, chord_id: 22},
  {key_id: 26, chord_id: 2},
  {key_id: 26, chord_id: 12},
  {key_id: 26, chord_id: 16},
  {key_id: 26, chord_id: 23},
  {key_id: 26, chord_id: 32},
  {key_id: 26, chord_id: 37},
  {key_id: 26, chord_id: 46},
  {key_id: 27, chord_id: 23},
  {key_id: 27, chord_id: 33},
  {key_id: 27, chord_id: 37},
  {key_id: 27, chord_id: 47},
  {key_id: 27, chord_id: 2},
  {key_id: 27, chord_id: 7},
  {key_id: 27, chord_id: 16},
  {key_id: 28, chord_id: 47},
  {key_id: 28, chord_id: 3},
  {key_id: 28, chord_id: 7},
  {key_id: 28, chord_id: 17},
  {key_id: 28, chord_id: 23},
  {key_id: 28, chord_id: 28},
  {key_id: 28, chord_id: 37},
  {key_id: 29, chord_id: 17},
  {key_id: 29, chord_id: 24},
  {key_id: 29, chord_id: 28},
  {key_id: 29, chord_id: 38},
  {key_id: 29, chord_id: 47},
  {key_id: 29, chord_id: 52},
  {key_id: 29, chord_id: 7},
  {key_id: 30, chord_id: 38},
  {key_id: 30, chord_id: 48},
  {key_id: 30, chord_id: 52},
  {key_id: 30, chord_id: 8},
  {key_id: 30, chord_id: 17},
  {key_id: 30, chord_id: 68},
  {key_id: 30, chord_id: 28}
])
ElementLibrary.create!([
  {name: "Intro"},
  {name: "Verse"},
  {name: "Pre-Chorus"},
  {name: "Chorus"},
  {name: "Bridge"},
  {name: "Solo"},
  {name: "Outro"}
])
Key.create!([
  {tonic: "C# Major", quality: "Major"},
  {tonic: "F# Major", quality: "Major"},
  {tonic: "B Major", quality: "Major"},
  {tonic: "E Major", quality: "Major"},
  {tonic: "A Major", quality: "Major"},
  {tonic: "D Major", quality: "Major"},
  {tonic: "G Major", quality: "Major"},
  {tonic: "C Major", quality: "Major"},
  {tonic: "F Major", quality: "Major"},
  {tonic: "Bb Major", quality: "Major"},
  {tonic: "Eb Major", quality: "Major"},
  {tonic: "Ab Major", quality: "Major"},
  {tonic: "Db Major", quality: "Major"},
  {tonic: "Gb Major", quality: "Major"},
  {tonic: "Cb Major", quality: "Major"},
  {tonic: "A# Minor", quality: "Minor"},
  {tonic: "D# Minor", quality: "Minor"},
  {tonic: "G# Minor", quality: "Minor"},
  {tonic: "C# Minor", quality: "Minor"},
  {tonic: "F# Minor", quality: "Minor"},
  {tonic: "B Minor", quality: "Minor"},
  {tonic: "E Minor", quality: "Minor"},
  {tonic: "A Minor", quality: "Minor"},
  {tonic: "D Minor", quality: "Minor"},
  {tonic: "G Minor", quality: "Minor"},
  {tonic: "C Minor", quality: "Minor"},
  {tonic: "F Minor", quality: "Minor"},
  {tonic: "Bb Minor", quality: "Minor"},
  {tonic: "Eb Minor", quality: "Minor"},
  {tonic: "Ab Minor", quality: "Minor"}
])

Tempo.create!([
  {bpm: 20, tempo_name: "Larghissimo", description: "very, very slow"},
  {bpm: 40, tempo_name: "Grave", description: "slow and solemn"},
  {bpm: 50, tempo_name: "Lento", description: "slowly"},
  {bpm: 60, tempo_name: "Largo", description: "broadly"},
  {bpm: 62, tempo_name: "Larghetto", description: "rather broadly"},
  {bpm: 64, tempo_name: "Larghetto", description: "rather broadly"},
  {bpm: 66, tempo_name: "Larghetto", description: "rather broadly"},
  {bpm: 68, tempo_name: nil, description: nil},
  {bpm: 70, tempo_name: nil, description: nil},
  {bpm: 72, tempo_name: nil, description: nil},
  {bpm: 74, tempo_name: nil, description: nil},
  {bpm: 76, tempo_name: nil, description: nil},
  {bpm: 78, tempo_name: nil, description: nil},
  {bpm: 80, tempo_name: nil, description: nil},
  {bpm: 82, tempo_name: nil, description: nil},
  {bpm: 84, tempo_name: nil, description: nil},
  {bpm: 86, tempo_name: nil, description: nil},
  {bpm: 88, tempo_name: nil, description: nil},
  {bpm: 90, tempo_name: nil, description: nil},
  {bpm: 92, tempo_name: nil, description: nil},
  {bpm: 94, tempo_name: nil, description: nil},
  {bpm: 96, tempo_name: nil, description: nil},
  {bpm: 98, tempo_name: nil, description: nil},
  {bpm: 100, tempo_name: nil, description: nil},
  {bpm: 102, tempo_name: nil, description: nil},
  {bpm: 104, tempo_name: nil, description: nil},
  {bpm: 106, tempo_name: nil, description: nil},
  {bpm: 108, tempo_name: nil, description: nil},
  {bpm: 110, tempo_name: nil, description: nil},
  {bpm: 112, tempo_name: nil, description: nil},
  {bpm: 114, tempo_name: nil, description: nil},
  {bpm: 116, tempo_name: nil, description: nil},
  {bpm: 118, tempo_name: nil, description: nil},
  {bpm: 120, tempo_name: nil, description: nil},
  {bpm: 122, tempo_name: nil, description: nil},
  {bpm: 124, tempo_name: nil, description: nil},
  {bpm: 126, tempo_name: nil, description: nil},
  {bpm: 128, tempo_name: nil, description: nil},
  {bpm: 130, tempo_name: nil, description: nil},
  {bpm: 132, tempo_name: nil, description: nil},
  {bpm: 134, tempo_name: nil, description: nil},
  {bpm: 136, tempo_name: nil, description: nil},
  {bpm: 138, tempo_name: nil, description: nil},
  {bpm: 140, tempo_name: nil, description: nil},
  {bpm: 142, tempo_name: nil, description: nil},
  {bpm: 144, tempo_name: nil, description: nil},
  {bpm: 146, tempo_name: nil, description: nil},
  {bpm: 148, tempo_name: nil, description: nil},
  {bpm: 150, tempo_name: nil, description: nil},
  {bpm: 152, tempo_name: nil, description: nil},
  {bpm: 154, tempo_name: nil, description: nil},
  {bpm: 156, tempo_name: nil, description: nil},
  {bpm: 158, tempo_name: nil, description: nil},
  {bpm: 160, tempo_name: nil, description: nil},
  {bpm: 162, tempo_name: nil, description: nil},
  {bpm: 164, tempo_name: nil, description: nil},
  {bpm: 166, tempo_name: nil, description: nil},
  {bpm: 168, tempo_name: nil, description: nil},
  {bpm: 170, tempo_name: nil, description: nil},
  {bpm: 172, tempo_name: nil, description: nil},
  {bpm: 174, tempo_name: nil, description: nil},
  {bpm: 176, tempo_name: nil, description: nil},
  {bpm: 178, tempo_name: nil, description: nil},
  {bpm: 180, tempo_name: nil, description: nil},
  {bpm: 182, tempo_name: nil, description: nil},
  {bpm: 184, tempo_name: nil, description: nil},
  {bpm: 186, tempo_name: nil, description: nil},
  {bpm: 188, tempo_name: nil, description: nil},
  {bpm: 190, tempo_name: nil, description: nil},
  {bpm: 192, tempo_name: nil, description: nil},
  {bpm: 194, tempo_name: nil, description: nil},
  {bpm: 196, tempo_name: nil, description: nil},
  {bpm: 198, tempo_name: nil, description: nil},
  {bpm: 200, tempo_name: nil, description: nil},
  {bpm: 202, tempo_name: nil, description: nil},
  {bpm: 204, tempo_name: nil, description: nil},
  {bpm: 206, tempo_name: nil, description: nil},
  {bpm: 208, tempo_name: nil, description: nil},
  {bpm: 210, tempo_name: nil, description: nil},
  {bpm: 212, tempo_name: nil, description: nil},
  {bpm: 214, tempo_name: nil, description: nil},
  {bpm: 216, tempo_name: nil, description: nil},
  {bpm: 218, tempo_name: nil, description: nil},
  {bpm: 220, tempo_name: nil, description: nil}
])
TimeSignature.create!([
  {beat_unit: 2, bar: 4, name: "2/4"},
  {beat_unit: 3, bar: 4, name: "3/4"},
  {beat_unit: 4, bar: 4, name: "4/4"},
  {beat_unit: 5, bar: 4, name: "5/4"},
  {beat_unit: 7, bar: 4, name: "7/4"},
  {beat_unit: 3, bar: 8, name: "3/8"},
  {beat_unit: 5, bar: 8, name: "5/8"},
  {beat_unit: 6, bar: 8, name: "6/8"},
  {beat_unit: 7, bar: 8, name: "7/8"},
  {beat_unit: 9, bar: 8, name: "9/8"},
  {beat_unit: 12, bar: 8, name: "12/8"}
])
